# Generated by Django 5.0.6 on 2024-07-03 12:49

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0004_alter_scored_data_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoredData',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=30)),
                ('DriveTrain', models.CharField(max_length=30)),
                ('EngineSize', models.FloatField()),
                ('Cylinders', models.IntegerField()),
                ('Horsepower', models.IntegerField()),
                ('MPG_City', models.FloatField()),
                ('Weight', models.FloatField()),
                ('Wheelbase', models.IntegerField()),
                ('P_MSRP', models.FloatField()),
                ('Created_At', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.DeleteModel(
            name='scored_data',
        ),
    ]
